[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 100
